services:
  db:
    container_name: courses-postgres
    image: postgres:15.8-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - courses_db-volume:/var/lib/postgresql/data

  pg:
    container_name: courses-pgadmin4
    image: dpage/pgadmin4:8.10
    restart: always
    depends_on:
      - db
    ports:
      - 5430:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASSWORD}
    volumes:
      - courses_pg-volume:/var/lib/pgadmin

volumes:
  courses_db-volume:
    external: false
  courses_pg-volume:
    external: false
